[build-system]
requires = ["hatchling>=1.18.0"]
build-backend = "hatchling.build"

[project]
name = "iva"
version = "0.1.0"
description = "ICS app classifier (BERT, BiLSTM, classical ML)"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }

dependencies = [
  "pandas>=1.3.0",
  "numpy>=1.21.0",
  "scikit-learn>=1.0.0",
  "nltk>=3.6.0",
  "langid>=1.1.6",
  "tqdm>=4.62.0",
]

[project.optional-dependencies]

# Install everything used across appclassifier scripts
all = [
  "torch>=1.9.0",
  "transformers>=4.12.0",
  "tensorflow>=2.8.0",
]

[project.urls]
Homepage = "https://anonymous.4open.science/r/iv-detector-2B82
Repository = "https://anonymous.4open.science/r/iv-detector-2B82"

[tool.iva]
# Convenience metadata about where the runnable scripts live
scripts_dir = "appclassifier"


